### PR TITLE
SUVI code in sunkit_instruments

### PR DESCRIPTION
**Pull request by nabobalis**
Rebase and update of #56

### CODE REVIEW

**Comment by nabobalis** [comment]
Hello @cbethge, I updated your PR and made some changes to the code you submitted.

When/if you have some time, if you could look over the `sunkit_instruments/suvi/suvi.py` and `sunkit_instruments/suvi/io.py` please?

These files contain the code you submitted with some tweaks here for style or just to remove some logic branches in order to simplify the code but not to remove functionally.

**Comment by cbethge** [comment]
Thanks, I agree with everything! Also, good news on the CONTINUE front: the L1b files should hopefully be fixed come October or November (going forward that is, the ones prior to that will still be broken). And another fyi: at some point there will be another major contribution to this code, it's for the PSF deconvolution. We are not quite there yet, but hopefully by the end of the year. The PSF code probably has as many lines of code as the entire contribution so far, just to give you a heads-up.

**Comment by nabobalis** [comment]
Thanks for the code @cbethge, I will try to get a release of this out soon.

**Comment by cbethge** [comment]
Great, thank you! I will let you know if I have more contributions, or if things change.

**Pull request merged**
